c_compiler_version:        # [linux]
  - 11                     # [linux]
cxx_compiler_version:      # [linux]
  - 11                     # [linux]
arm_variant_target:
  - None                    # [not (linux and aarch64)] 
  - sbsa                    # [linux and aarch64]
#  - tegra                  # [linux and aarch64]
cross_target_platform:
  - None           # [not (linux or win)]
  - linux-64       # [linux and x86_64]
  - linux-aarch64  # [linux and aarch64]
#  - linux-aarch64  # [linux and aarch64]
  - win-64         # [win]
# https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#virtual-architecture-feature-list
# https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#gpu-feature-list
DEFAULT_CUDAARCHS:
  - "50-real;52-real;60-real;61-real;70-real;75-real;80-real;86-real;89-real;90-real;100-real;101-real;120"
#  - "72-real;87"  # [linux and aarch64]
DEFAULT_TORCH_CUDA_ARCH_LIST:
  - "5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.9;9.0;10.0;10.1;12.0+PTX"
#  - "7.2;8.7+PTX"  # [linux and aarch64]

zip_keys:
  - arm_variant_target
  - cross_target_platform
  - DEFAULT_CUDAARCHS
  - DEFAULT_TORCH_CUDA_ARCH_LIST
