# Important change for generating the correct graph on PBP:
#  * Added 'not (linux and aarch64)' selector to 'None' entry.
#  * Changed 'linux' selector to 'linux and aarch64' for 'sbsa' entry.
# These changes would make sure the build graph is correctly generated on PBP.
arm_variant_target:
  - None                   # [not (linux and aarch64)]
  - sbsa                   # [linux and aarch64]

# Important change for generating the correct graph on PBP:
#  * Changed 'linux' selector to 'linux and x86_64' for 'linux-64' entry.
#  * Changed 'linux' selector to 'linux and aarch64' for 'linux-aarch64' entry.
# These changes would make sure the build graph is correctly generated on PBP,
# and eliminate cross-build targets, such as 'aarch64' build on 'linux64' host.
cross_target_platform:
  - None           # [not (linux or win)]
  - linux-64       # [linux and x86_64]
  - linux-aarch64  # [linux and aarch64]
  - win-64         # [win]

# Important change for generating the correct graph on PBP:
#  * Added 'not (linux and aarch64)' selector to the 1st entry.
# These changes would make sure the build graph is correctly generated on PBP.
DEFAULT_CUDAARCHS:
  - "75-real;80-real;86-real;89-real;90a-real;100f-real;103f-real;120a-real;121f-real;121-virtual"  # [not (linux and aarch64)]
  # aarch64 has more targets than x86 because Tegra devices are sbsa aarch64 only
  - "75-real;80-real;86-real;87-real;89-real;90a-real;100f-real;103f-real;110-real;120a-real;121f-real;121-virtual"  # [linux and aarch64]

zip_keys:
  - arm_variant_target
  - cross_target_platform
  - DEFAULT_CUDAARCHS
